spring:
  cloud:
    vault:
      uri: http://localhost:8200
      token: ${VAULT_TOKEN:root-token}
      kv:
        enabled: true
        backend: secret
        application-name: ap10981/prod/secret-prod
      authentication: TOKEN
      fail-fast: true
      config:
        lifecycle:
          min-renewal: 10s
          expiry-threshold: 1m
          
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
  endpoint:
    health:
      show-details: always
      
logging:
  level:
    org.springframework.cloud.vault: ERROR
    com.example.vault: WARN
    
server:
  port: 8083

# Profil production - configuration sp√©cifique
app:
  profile: production
  environment: prod
  debug: false