spring:
  cloud:
    vault:
      uri: http://localhost:8200
      token: ${VAULT_TOKEN:root-token}
      kv:
        enabled: true
        backend: secret
        application-name: ap10981/test/secret-test
      authentication: TOKEN
      fail-fast: true
      config:
        lifecycle:
          min-renewal: 10s
          expiry-threshold: 1m
          
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
  endpoint:
    health:
      show-details: always
      
logging:
  level:
    org.springframework.cloud.vault: INFO
    com.example.vault: INFO
    
server:
  port: 8081

# Profil test - configuration sp√©cifique
app:
  profile: testing
  environment: test
  debug: false